### ISSUE TITLE
getting error when using local broker

### ISSUE THREAD

**Issue by sisomm** [walterhiggins/scriptcraft-extras-mqtt#2]
Hi, I got it working1 

However, i get this error when running in the console

> js client.connect();
> 11:50:56 [INFO] [scriptcraft] connectionLost: Connection lost (32109) - java.io.EOFException

but it seems to work, that is - it can send messages

**Comment by walterhiggins** [comment]
It's not an error - it's just that the previous client's connection was lost. I'm guessing you must have had 2 clients with same client id?

**Comment by sisomm** [comment]
Ah thanks.
