### ISSUE TITLE
How to get errors when javascript files have wrong syntax

### ISSUE THREAD

**Issue by sisomm** [walterhiggins/scriptcraft-extras-mqtt#4]
Hi Walter, 

How can I get the parse errors? Is there a log file? Now the console is very quiet if a malformed javascript file is parsed,

**Comment by walterhiggins** [comment]
Hi Simen,

This is actually a problem I recently fixed in the ScriptCraft project. It should be available in the next release of ScriptCraft or you can build from source (if you're comfortable with that)

https://github.com/walterhiggins/ScriptCraft/commit/7a7767c83c21d07d3aac3b02b69396726b559ba2

**Comment by sisomm** [comment]
thanks. Much appreciated
